//
//  GradientSnippet.swift
//  VividGradients
//
//  Exports the current config as a self-contained SwiftUI view — source you
//  can paste into any other iOS 18+ app with no VividGradients files.
//
//  The template below mirrors GradientCanvasView + the mesh/motion maths in
//  GradientConfig. It's verified by type-checking against the iOS SDK; if the
//  renderer changes, update this string to match.
//

import SwiftUI

extension GradientStore {
    var configSwiftSnippet: String {
        let escaped = compactConfigJSON
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")

        return """
//  PortableGradient.swift
//  Generated by VividGradients — self-contained, no other files needed.
//  Requires iOS 18+ (MeshGradient). Reproduces the mesh, motion, rotation and
//  blur; the film-grain noise overlay is not included.

import SwiftUI

struct PortableGradient: View {
    static let configJSON = "\(escaped)"

    struct RGBA: Decodable {
        var red = 0.0, green = 0.0, blue = 0.0, opacity = 1.0
        var color: Color { Color(.sRGB, red: red, green: green, blue: blue, opacity: opacity) }
    }

    struct Config: Decodable {
        var background = RGBA()
        var colors: [RGBA] = []
        var gridWidth = 4
        var gridHeight = 4
        var smoothsColors = true
        var motion = "drift"
        var isAnimating = true
        var velocity = 1.0
        var amplitude = 0.16
        var animateEdges = false
        var motionSeed = 0.0
        var frameRate = 60
        var blurRadius = 0.0
        var rotation = 0.0
    }

    let config: Config = {
        (try? JSONDecoder().decode(Config.self, from: Data(PortableGradient.configJSON.utf8))) ?? Config()
    }()

    @State private var start = Date()

    var body: some View {
        GeometryReader { geo in
            TimelineView(.animation(minimumInterval: 1.0 / Double(config.frameRate),
                                    paused: !config.isAnimating)) { timeline in
                let phase = timeline.date.timeIntervalSince(start) * config.velocity
                MeshGradient(
                    width: config.gridWidth,
                    height: config.gridHeight,
                    points: meshPoints(at: phase),
                    colors: meshColors,
                    background: config.background.color,
                    smoothsColors: config.smoothsColors
                )
                .rotationEffect(.degrees(config.rotation))
                .scaleEffect(coverScale(size: geo.size, degrees: config.rotation))
                .blur(radius: CGFloat(config.blurRadius))
            }
        }
        .ignoresSafeArea()
    }

    private var meshColors: [Color] {
        let need = config.gridWidth * config.gridHeight
        var result = config.colors.map { $0.color }
        if result.count < need {
            result += Array(repeating: result.last ?? .black, count: need - result.count)
        } else if result.count > need {
            result = Array(result.prefix(need))
        }
        return result
    }

    private func meshPoints(at phase: Double) -> [SIMD2<Float>] {
        let w = config.gridWidth
        let h = config.gridHeight
        let motion = Motion(rawValue: config.motion) ?? .drift
        var points: [SIMD2<Float>] = []
        points.reserveCapacity(w * h)
        for row in 0..<h {
            for col in 0..<w {
                let hx: Double = w > 1 ? Double(col) / Double(w - 1) : 0.5
                let hy: Double = h > 1 ? Double(row) / Double(h - 1) : 0.5
                let onSideEdge = (col == 0 || col == w - 1)
                let onTopEdge = (row == 0 || row == h - 1)
                let isCorner = onSideEdge && onTopEdge
                let isInterior = !onSideEdge && !onTopEdge
                let canMove = isInterior || (config.animateEdges && !isCorner)
                var px = hx
                var py = hy
                if canMove && motion != .still {
                    let seed = vertexSeed(col: col, row: row)
                    let moved = motion.position(home: CGPoint(x: hx, y: hy),
                                                phase: phase, seed: seed, amplitude: config.amplitude)
                    if isInterior {
                        px = min(max(Double(moved.x), 0.04), 0.96)
                        py = min(max(Double(moved.y), 0.04), 0.96)
                    } else if onTopEdge {
                        px = min(max(Double(moved.x), 0.06), 0.94)
                    } else {
                        py = min(max(Double(moved.y), 0.06), 0.94)
                    }
                }
                points.append(SIMD2<Float>(Float(px), Float(py)))
            }
        }
        return points
    }

    private func vertexSeed(col: Int, row: Int) -> Double {
        let raw = sin(Double(col) * 12.9898 + Double(row) * 78.233) * 43758.5453
        let frac = raw - floor(raw)
        let shifted = frac + config.motionSeed
        return shifted - floor(shifted)
    }

    private func coverScale(size: CGSize, degrees: Double) -> CGFloat {
        let radians = degrees * .pi / 180
        let c = abs(cos(radians))
        let s = abs(sin(radians))
        let w = max(Double(size.width), 1)
        let h = max(Double(size.height), 1)
        return CGFloat(max((w * c + h * s) / w, (h * c + w * s) / h))
    }

    enum Motion: String {
        case still, drift, orbit, bounce, swirl, jitter
        case flag, radiance, ripple, pendulum, figureEight, spiral

        func position(home: CGPoint, phase p: Double, seed: Double, amplitude a: Double) -> CGPoint {
            let hx = Double(home.x)
            let hy = Double(home.y)
            let s: Double = seed * 2 * .pi
            switch self {
            case .still:
                return home
            case .drift:
                let dx: Double = a * (0.7 * sin(p * 0.53 + s) + 0.3 * sin(p * 0.31 + s * 2.3))
                let dy: Double = a * (0.7 * cos(p * 0.47 + s * 1.7) + 0.3 * cos(p * 0.23 + s * 3.1))
                return CGPoint(x: hx + dx, y: hy + dy)
            case .orbit:
                let dx: Double = a * cos(p * 0.6 + s)
                let dy: Double = a * sin(p * 0.6 + s)
                return CGPoint(x: hx + dx, y: hy + dy)
            case .bounce:
                let dx: Double = a * Self.triangle(p * 0.18 + seed)
                let dy: Double = a * Self.triangle(p * 0.13 + seed * 1.7)
                return CGPoint(x: hx + dx, y: hy + dy)
            case .swirl:
                let rx: Double = hx - 0.5
                let ry: Double = hy - 0.5
                let angle: Double = p * 0.35 + s * 0.15
                let breath: Double = 1 + a * sin(p * 0.5 + s)
                let x: Double = 0.5 + (rx * cos(angle) - ry * sin(angle)) * breath
                let y: Double = 0.5 + (rx * sin(angle) + ry * cos(angle)) * breath
                return CGPoint(x: x, y: y)
            case .jitter:
                let dx: Double = a * 0.25 * (sin(p * 6.3 + s * 3) + sin(p * 9.7 + s * 7))
                let dy: Double = a * 0.25 * (cos(p * 7.1 + s * 5) + cos(p * 11.3 + s * 2))
                return CGPoint(x: hx + dx, y: hy + dy)
            case .flag:
                let travel: Double = sin(hx * 6.0 - p * 2.0 + s)
                let anchor: Double = 0.35 + 0.65 * hx
                let dy: Double = a * travel * anchor
                let dx: Double = a * 0.15 * cos(hx * 6.0 - p * 2.0 + s)
                return CGPoint(x: hx + dx, y: hy + dy)
            case .radiance:
                let rx: Double = hx - 0.5
                let ry: Double = hy - 0.5
                let len: Double = max(1e-4, (rx * rx + ry * ry).squareRoot())
                let pulse: Double = sin(p * 0.9 + s * 0.2)
                let scale: Double = a * pulse / len
                return CGPoint(x: hx + rx * scale, y: hy + ry * scale)
            case .ripple:
                let rx: Double = hx - 0.5
                let ry: Double = hy - 0.5
                let len: Double = max(1e-4, (rx * rx + ry * ry).squareRoot())
                let wave: Double = sin(len * 9.0 - p * 2.0 + s * 0.3)
                let scale: Double = a * wave / len
                return CGPoint(x: hx + rx * scale, y: hy + ry * scale)
            case .pendulum:
                let swing: Double = sin(p * 0.9 + s)
                let dx: Double = a * swing
                let dy: Double = a * 0.25 * (1 - cos(p * 1.8 + s * 2))
                return CGPoint(x: hx + dx, y: hy + dy)
            case .figureEight:
                let t: Double = p * 0.7
                let dx: Double = a * sin(t + s)
                let dy: Double = a * 0.6 * sin(2 * t + s)
                return CGPoint(x: hx + dx, y: hy + dy)
            case .spiral:
                let angle: Double = p * 0.8 + s
                let radius: Double = a * (0.35 + 0.65 * (0.5 + 0.5 * sin(p * 0.33 + s)))
                let dx: Double = radius * cos(angle)
                let dy: Double = radius * sin(angle)
                return CGPoint(x: hx + dx, y: hy + dy)
            }
        }

        private static func triangle(_ x: Double) -> Double {
            let f = x - floor(x)
            return 4 * abs(f - 0.5) - 1
        }
    }
}
"""
    }

    private var compactConfigJSON: String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(config) else { return "{}" }
        return String(decoding: data, as: UTF8.self)
    }
}
