//
//  GradientSnippet.swift
//  VividGradients example
//
//  Exports the current config as a ready-to-paste SwiftUI view in the same
//  form as the package README: `import VividGradients`, then
//  `GradientView(config:)` with a `makeConfig()` that rebuilds this exact look.
//

import SwiftUI
import VividGradients

extension GradientStore {
    var configSwiftSnippet: String {
        // Start from the active preset when there is one, so the snippet only
        // lists the values that differ — exactly how the README example reads.
        let base: GradientConfig
        let baseExpr: String
        if let preset = activePreset {
            base = preset.config
            baseExpr = "GradientPreset.\(preset.rawValue).config"
        } else {
            base = GradientConfig()
            baseExpr = "GradientConfig()"
        }

        var out: [String] = [
            "//  GradientBackground.swift",
            "//  Generated by VividGradients — add the package at",
            "//  https://github.com/zafe/vivid-gradients, then drop this in. iOS 18+.",
            "",
            "import SwiftUI",
            "import VividGradients",
            "",
            "struct GradientBackground: View {",
            "    var body: some View {",
            "        GradientView(config: makeConfig())",
            "    }",
            "",
            "    func makeConfig() -> GradientConfig {",
            "        var config = \(baseExpr)",
        ]

        func add(_ property: String, _ value: String) {
            out.append("        config.\(property) = \(value)")
        }

        if config.gridWidth != base.gridWidth { add("gridWidth", "\(config.gridWidth)") }
        if config.gridHeight != base.gridHeight { add("gridHeight", "\(config.gridHeight)") }
        if config.colors != base.colors {
            out.append("        config.colors = [")
            for color in config.colors { out.append("            \(rgba(color)),") }
            out.append("        ]")
        }
        if config.background != base.background { add("background", rgba(config.background)) }
        if config.smoothsColors != base.smoothsColors { add("smoothsColors", "\(config.smoothsColors)") }
        if config.motion != base.motion { add("motion", ".\(config.motion.rawValue)") }
        if config.isAnimating != base.isAnimating { add("isAnimating", "\(config.isAnimating)") }
        if config.velocity != base.velocity { add("velocity", g(config.velocity)) }
        if config.amplitude != base.amplitude { add("amplitude", g(config.amplitude)) }
        if config.animateEdges != base.animateEdges { add("animateEdges", "\(config.animateEdges)") }
        if config.motionSeed != base.motionSeed { add("motionSeed", g(config.motionSeed)) }
        if config.frameRate != base.frameRate { add("frameRate", "\(config.frameRate)") }
        if config.blurRadius != base.blurRadius { add("blurRadius", g(config.blurRadius)) }
        if config.rotation != base.rotation { add("rotation", g(config.rotation)) }
        if config.noiseOpacity != base.noiseOpacity { add("noiseOpacity", g(config.noiseOpacity)) }
        if config.noiseGranularity != base.noiseGranularity { add("noiseGranularity", g(config.noiseGranularity)) }
        if config.noiseBlend != base.noiseBlend { add("noiseBlend", ".\(config.noiseBlend.rawValue)") }
        if config.noiseAnimated != base.noiseAnimated { add("noiseAnimated", "\(config.noiseAnimated)") }
        if config.noiseFrameRate != base.noiseFrameRate { add("noiseFrameRate", g(config.noiseFrameRate)) }

        out.append("        return config")
        out.append("    }")
        out.append("}")
        return out.joined(separator: "\n")
    }

    /// Compact, round-trippable Double literal (0.6 not 0.6000000001).
    private func g(_ value: Double) -> String { String(format: "%g", value) }

    private func rgba(_ color: RGBAColor) -> String {
        "RGBAColor(red: \(g(color.red)), green: \(g(color.green)), blue: \(g(color.blue)), opacity: \(g(color.opacity)))"
    }
}
